import { $ } from 'bun';
import path from 'path';
import process from 'process';
import fs from 'fs/promises';

const Paths = {
  codegen: {
    root: './packages/typsi/.codegen',
    codex: {
      root: './packages/typsi/.codegen/codex',
      emoji: './packages/typsi/.codegen/codex/src/modules/emoji.txt',
      sym: './packages/typsi/.codegen/codex/src/modules/sym.txt',
    },
  },
  src: {
    customRules: './packages/typsi/src/custom-rules.txt',
  },
  typsi: {
    root: './packages/typsi',
  },
  generated: {
    emoji: './packages/typsi/generated/emoji.yml',
    sym: './packages/typsi/generated/sym.yml',
    customRules: './packages/typsi/generated/custom-rules.yml',
  },
  packageYml: './packages/typsi/package.yml',
};

const args = process.argv.slice(2);
const flags = {
  force: args.some(simpleFlag({ short: 'f', long: 'force' })),
};

if (flags.force) {
  try {
    await fs.rm(Paths.codegen.root, { recursive: true });
  } catch {}
}
if (!(await fs.exists(Paths.codegen.root))) {
  await fs.mkdir(Paths.codegen.root, { recursive: true });
}

if (!(await fs.exists(Paths.codegen.codex.root))) {
  await fs.mkdir(Paths.codegen.codex.root, { recursive: true });
  $.cwd(path.join(process.cwd(), Paths.codegen.codex.root));

  await $`git init`;
  await $`git remote add origin https://github.com/typst/codex`;
  await $`git fetch origin main`;
  await $`git checkout origin/main -- src/modules/emoji.txt src/modules/sym.txt`;
}

const targetSeq: Array<{ path: string; output: string; surround: string }> = [
  {
    path: Paths.codegen.codex.emoji,
    output: Paths.generated.emoji,
    surround: ':',
  },
  {
    path: Paths.codegen.codex.sym,
    output: Paths.generated.sym,
    surround: '\\',
  },
  {
    path: Paths.src.customRules,
    output: Paths.generated.customRules,
    surround: '\\',
  },
];

for (const target of targetSeq) {
  const src = await fs.readFile(target.path, {
    encoding: 'utf-8',
  });
  const parsed = parse(src);
  const file = generateEspansoFile(target.surround, parsed);
  await fs.mkdir(path.dirname(target.output), { recursive: true });
  await fs.writeFile(target.output, file, { encoding: 'utf-8' });
}
await fs.writeFile(
  Paths.packageYml,
  `# Generated by Typsi\n\nincludes:\n${targetSeq
    .map(
      (target) => `  - ${path.posix.relative(Paths.typsi.root, target.output)}`,
    )
    .join('\n')}\n`,
  {
    encoding: 'utf-8',
  },
);

function parse(content: string): Replacement[] {
  const result: Replacement[] = [];

  let mostRecentDeprecation: string | null = null;
  let mostRecentStem: string | null = null;
  for (const line of content.split(/\r?\n/)) {
    if (line.trim().length === 0) {
      continue;
    }

    let match: RegExpMatchArray | null;
    if ((match = /^[ ]*\/\/[ ]+(.+)$/.exec(line))) {
      // comment
    } else if ((match = /^@(.*)$/.exec(line))) {
      mostRecentDeprecation = match[1]!;
    } else if ((match = /^[ ]*([^ .][^ ]*)[ ]*(.*)$/.exec(line))) {
      let [_, name, value] = match;
      name = refineString(name);
      value = refineString(value);
      if (value) {
        result.push({
          match: name,
          replacement: value,
          deprecation: mostRecentDeprecation,
        });
      }
      mostRecentStem = name;
      mostRecentDeprecation = null;
    } else if ((match = /^[ ]*(\.[^ ]+)[ ]*(.*)$/.exec(line))) {
      let [_, name, value] = match;
      name = refineString(name);
      value = refineString(value);
      if (value) {
        result.push({
          match: mostRecentStem + name,
          replacement: value,
          deprecation: mostRecentDeprecation,
        });
      }
      mostRecentDeprecation = null;
    } else {
      console.log(JSON.stringify(line));
    }
  }

  return result;
}

interface Replacement {
  match: string;
  replacement: string;
  deprecation: string | null;
}

function generateEspansoFile(surround: string, entries: Replacement[]): string {
  const lines = entries.map((replacement) =>
    generateEspansoEntry(surround, replacement)
      .split('\n')
      .map((line) => `  ${line}`)
      .join('\n'),
  );

  return `# Generated by Typsi\nmatches:\n${lines.join('\n')}`;
}

function generateEspansoEntry(
  surround: string,
  replacement: Replacement,
): string {
  return `${
    replacement.deprecation ? `# ${replacement.deprecation}\n` : ''
  }- { trigger: ${JSON.stringify(
    `${surround}${replacement.match}${surround}`,
  )}, replace: ${JSON.stringify(replacement.replacement)} }`;
}

function simpleFlag({
  short,
  long,
}: {
  short?: string;
  long?: string;
}): (arg: string) => boolean {
  return (arg) => {
    if (arg == `--${long}`) return true;
    if (arg.length < 2) return false;
    if (arg[0] !== '-' || arg[1] === '-') return false;
    return arg.slice(1).includes('f');
  };
}

function refineString(text: string | undefined): string {
  if (typeof text !== 'string') return '';
  if (text.at(0) === '"') {
    try {
      return JSON.parse(text);
    } catch {}
  }
  return text;
}
